# Generated by Django 4.2.16 on 2024-11-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_module', '0003_userquizattempt_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
