# Generated by Django 4.2.16 on 2024-11-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_module', '0004_question_answer'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userquizattempt',
            index=models.Index(fields=['id', 'status'], name='test_module_id_d62726_idx'),
        ),
    ]
